## Getting Dataset from PlayStore

In [1]:
pip install google-play-scraper

Collecting google-play-scraper
  Using cached google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
Using cached google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7
Note: you may need to restart the kernel to use updated packages.

In [2]:
from google_play_scraper import reviews
from google_play_scraper import Sort

import pandas as pd

In [3]:
APP_ID = "com.theaa.android.theaa"

In [14]:
result, continuation_token = reviews(
    APP_ID,
    lang="en",
    country="gb",
    sort=Sort.NEWEST,
    count=2000
)

In [16]:
result[0]

{'reviewId': 'f9483d79-8f76-469d-b5c5-4274b7b432ef',
 'userName': 'Gary Parkinson',
 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjURxjjHbH1S5rgs8OigHlbmg6UUe9kfr3kqDqLpevbT1Ntb0Q8v',
 'content': 'Great app...',
 'score': 5,
 'thumbsUpCount': 0,
 'reviewCreatedVersion': '11.18.0',
 'at': datetime.datetime(2026, 6, 24, 11, 55, 38),
 'replyContent': None,
 'repliedAt': None,
 'appVersion': '11.18.0'}

In [17]:
df = pd.DataFrame(result)

In [18]:
df.columns

Index(['reviewId', 'userName', 'userImage', 'content', 'score',
       'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent',
       'repliedAt', 'appVersion'],
      dtype='object')

In [19]:
df = df[
    [
        "reviewId",
        "content",
        "score",
        "at",
        "thumbsUpCount",
        "appVersion"
    ]
]

In [20]:
df.head()

,reviewId,content,score,at,thumbsUpCount,appVersion
0,f9483d79-8f76-469d-b5c5-4274b7b432ef,Great app...,5,2026-06-24 11:55:38,0,11.18.0
1,7888b5ed-f169-4f0c-8ba6-5dac9fb86da8,easy too use,5,2026-06-24 11:40:10,0,11.18.0
2,c47b8a28-8ba9-47f6-b79d-ccc40bcc3ec2,great,5,2026-06-24 10:38:35,0,11.12.0
3,7257c00f-5307-4b1f-8871-375cbd71ab16,useful information and good benefits thanks ⁹,5,2026-06-23 23:22:45,0,11.18.0
4,6a47dcf4-e466-4c06-bf2c-13b290088f84,"very responsive, with accurate identification ...",5,2026-06-23 20:04:45,0,11.18.0

In [21]:
df.to_csv(
    "aa_reviews.csv",
    index=False
)

In [22]:
df["score"].value_counts().sort_index()

score
1     197
2      56
3      53
4     143
5    1551
Name: count, dtype: int64

In [23]:
negative_reviews = df[df["score"] <= 2]

In [24]:
negative_reviews

,reviewId,content,score,at,thumbsUpCount,appVersion
15,50703514-042b-4275-8013-98db2573dfb4,rubbish as misleading and inaccurate,1,2026-06-22 11:11:52,0,11.18.0
25,3a0edfc1-129a-44b1-95cf-ff9b641c518b,AA app not working. Totally usless app. cant e...,1,2026-06-20 15:13:51,0,11.18.0
30,76b2ac7d-4db3-4fda-8f50-e91eb78387ea,stop sending stupid notifications about the we...,1,2026-06-19 21:23:33,1,11.18.0
33,a55d870b-3200-488e-bac5-e48a1dad3cd6,trying to sign into the app but telling me my ...,2,2026-06-19 15:34:47,0,11.17.1
40,f4ae8594-60fa-40a8-8581-fba3d1bbb4d3,wont let me access my a,1,2026-06-18 16:43:49,0,11.17.1
...,...,...,...,...,...,...
1990,4623558b-2359-4bc5-b13f-bc954d26f9af,I don't rate it,1,2025-09-08 19:36:30,0,11.1.8
1991,e8ffaae8-5f76-445f-80bf-523cdc3f426c,awkward to use.,1,2025-09-08 17:58:57,0,11.1.8
1996,cd175eff-7ffd-4914-b123-902770b0eabb,can't easily find traffic info,1,2025-09-08 11:36:28,0,11.1.8
1998,9c6bb82f-cdcf-41aa-bc7f-7ad63d3f3326,not working i can't change my car,1,2025-09-08 10:29:09,0,11.1.8
1999,de834ef4-f759-4364-a2b0-b766d7f13e94,"App ""tracking"" not working, get spammed every ...",2,2025-09-08 01:13:55,1,11.1.8

In [31]:
negative_reviews.content.iloc[2]

"stop sending stupid notifications about the weather and other nonsense. I don't mind getting a notification for when my car needs a service, but I don't care about other pointless things. edit - thanks for the reply. but I don't want to stop all notifications. I want notifications about my MOT etc. But the AA app should not be sending motivations that are totally irrelevant. I've got plenty of other apps for that."